### ISSUE TITLE
2.2.0-RC1 nftables not removing inet miniupnpd forward rules

### ISSUE THREAD

**Issue by JAMESMTL** [miniupnp/miniupnp#481]
Good Afternoon,

ok it's official I'm stuck. Rules that expire or which I delete explicitly via upnpc will not delete the inet forwarding rule. ex:

```
table inet miniupnpd {
	chain MINIUPNPD {
		type filter hook forward priority -25; policy accept;
		iif "ppp0" th dport 8000 @nh,128,32 3232236082 @nh,72,8 6 accept
	}
}
table ip miniupnpd {
	chain MINIUPNPD {
		type nat hook prerouting priority dstnat; policy accept;
	}

	chain MINIUPNPD-POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
	}
}
table ip6 miniupnpd {
	chain MINIUPNPD {
		type nat hook prerouting priority dstnat; policy accept;
	}

	chain MINIUPNPD-POSTROUTING {
		type nat hook postrouting priority srcnat; policy accept;
	}
}
```
Nothing unusual shows up in the syslog

```
grep miniupnpd /tmp/log/syslog
2020-07-04T14:53:05.589251-04:00 CENTURION systemd[1]: miniupnpd.service: Can't open PID file /run/miniupnpd.pid (yet?) after start: No such file or directory
2020-07-04T14:53:05.589663-04:00 CENTURION miniupnpd[2387]: HTTP listening on port 37783
2020-07-04T14:53:05.589751-04:00 CENTURION miniupnpd[2387]: Listening for NAT-PMP/PCP traffic on port 5351
2020-07-04T14:59:25.840678-04:00 CENTURION miniupnpd[2387]: remove port mapping 8000 TCP because it has expired

```
I have tried rebuilding minupnpd numerous times in my normal build environment as well as on a fresh install of buster but the results are the same.  The build log for the above example can be found here https://pastebin.com/raw/mquXgbGM

This is running on a box with a kernel that includes a custom bnx2x kernel module and all nftables config options enabled. built directly from the kernel stable branch.

```
uname -a
Linux CENTURION 5.7.5-bnx2x #1 SMP Wed Jun 24 11:29:29 EDT 2020 x86_64 GNU/Linux
```
```
miniupnpd --version
miniupnpd 2.2.0-RC1 master-fca45a6 Jul  4 2020
using netfilter(nftables) backend
```

nftables was installed from backports

```
apt list --installed | grep nft

libnftables1/buster-backports,now 0.9.3-2~bpo10+1 amd64 [installed,automatic]
libnftnl11/buster-backports,now 1.1.5-1~bpo10+1 amd64 [installed]
nftables/buster-backports,now 0.9.3-2~bpo10+1 amd64 [installed]
```

in an effort eliminate the possibility of user error during the kernel build I installed 5.6.0 from backports

```
uname -a
Linux CENTURION 5.6.0-0.bpo.2-amd64 #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) x86_64 GNU/Linux
```

Unfortunately I'm still seeing the exact same issue.

Here is the miniupnpd log when running when running with -d

```
miniupnpd[3350]: system uptime is 764 seconds
miniupnpd[3350]: mnl_socket bound, port_id=3350
miniupnpd[3350]: version 2.2.0-RC1 starting NAT-PMP/PCP UPnP-IGD ext if ppp0 BOOTID=1593891116
miniupnpd[3350]: HTTP listening on port 36245
miniupnpd[3350]: Listening for NAT-PMP/PCP traffic on port 5351
miniupnpd[3350]: HTTP REQUEST from 192.168.2.173:37950 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: HTTP REQUEST from 192.168.2.173:37952 : GET /L3F.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: HTTP REQUEST from 192.168.2.173:37954 : GET /WANCfg.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: HTTP REQUEST from 192.168.2.173:37956 : GET /WANIPCn.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64593 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: HTTP REQUEST from 192.168.2.50:54405 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1 (ver=1)
miniupnpd[3350]: SSDP M-SEARCH from 192.168.2.39:56788 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
miniupnpd[3350]: Single search found
miniupnpd[3350]: SendSSDPResponse(): 0 bytes to 192.168.2.39:56788 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN: uuid:92c506d8-f9e7-47a8-85af-5bf92a3b049d::urn:schemas-upnp-org:device:InternetGatewayDevice:1
EXT:
SERVER: Debian/buster UPnP/1.1 MiniUPnPd/2.2.0-RC1
LOCATION: http://192.168.2.1:36245/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1593891116
BOOTID.UPNP.ORG: 1593891116
CONFIGID.UPNP.ORG: 1337

miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64594 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64595 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetStatusInfo
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64596 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64597 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64598 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping
miniupnpd[3350]: AddPortMapping: ext port 8000 to 192.168.2.50:8000 protocol TCP for: libminiupnpc leaseduration=300 rhost=
miniupnpd[3350]: UPnP permission rule 0 matched : port mapping accepted
miniupnpd[3350]: redirecting port 8000 to 192.168.2.50:8000 protocol TCP for: libminiupnpc
miniupnpd[3350]: timestamp entry added (8000, 6, 1088)
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64599 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetSpecificPortMappingEntry
miniupnpd[3350]: timestamp entry found (8000, 6, 1088)
miniupnpd[3350]: GetSpecificPortMappingEntry: rhost='' 8000 TCP found => 192.168.2.50:8000 desc='libminiupnpc' duration=300
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1 (ver=1)
miniupnpd[3350]: SSDP M-SEARCH from 192.168.2.39:56796 ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
miniupnpd[3350]: Single search found
miniupnpd[3350]: SendSSDPResponse(): 0 bytes to 192.168.2.39:56796 ST: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=120
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1
USN: uuid:92c506d8-f9e7-47a8-85af-5bf92a3b049d::urn:schemas-upnp-org:device:InternetGatewayDevice:1
EXT:
SERVER: Debian/buster UPnP/1.1 MiniUPnPd/2.2.0-RC1
LOCATION: http://192.168.2.1:36245/rootDesc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 1593891116
BOOTID.UPNP.ORG: 1593891116
CONFIGID.UPNP.ORG: 1337

miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64600 : GET /rootDesc.xml (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64601 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetStatusInfo
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64602 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress
miniupnpd[3350]: HTTP REQUEST from 192.168.2.39:64603 : POST /ctl/IPConn (HTTP/1.1)
miniupnpd[3350]: Host: 192.168.2.1:36245
miniupnpd[3350]: SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#DeletePortMapping
miniupnpd[3350]: DeletePortMapping: external port: 8000, protocol: TCP
miniupnpd[3350]: removing redirect rule port 8000 TCP
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: ST: urn:dial-multiscreen-org:service:dial:1 (ver=1)
miniupnpd[3350]: SSDP M-SEARCH from 192.168.2.39:56804 ST: urn:dial-multiscreen-org:service:dial:1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: ST: urn:dial-multiscreen-org:service:dial:1 (ver=1)
miniupnpd[3350]: SSDP M-SEARCH from 192.168.2.39:56804 ST: urn:dial-multiscreen-org:service:dial:1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: ST: urn:dial-multiscreen-org:service:dial:1 (ver=1)
miniupnpd[3350]: SSDP M-SEARCH from 192.168.2.39:56804 ST: urn:dial-multiscreen-org:service:dial:1
miniupnpd[3350]: level=0 type=8
miniupnpd[3350]: ifindex = 3  192.168.2.1
miniupnpd[3350]: ST: urn:dial-multiscreen-org:service:dial:1 (ver=1)
miniupnpd[3350]: SSDP M-SEARCH from 192.168.2.39:56804 ST: urn:dial-multiscreen-org:service:dial:1
miniupnpd[3350]: shutting down MiniUPnPd
miniupnpd[3350]: send_batch: mnl_cb_run returned -1
miniupnpd[3350]: send_batch: mnl_cb_run returned -1
```

Any guidance would be appreciated. 
Thanks
James

**Comment by JAMESMTL** [comment]
This can be reproduced when upnp_forward_chain = upnp_nat_chain within miniupnpd.conf.

**Comment by miniupnp** [comment]
@JAMESMTL could you check with the latest master of miniupnpd ? the error logging has been improved !

**Comment by JAMESMTL** [comment]
miniupnpd 2.2.0-RC1 master-426f9a1 Sep 24 2020
using netfilter(nftables) backend

The results are the same as posted above
```
2020-09-24T20:17:03.849477-04:00 CENTURION miniupnpd[12628]: send_batch: mnl_cb_run returned -1 
2020-09-24T20:17:03.849642-04:00 CENTURION miniupnpd[12628]: chain_op(5, 2, miniupnpd, , nat, 4, 100) send_batch failed -4
```

it's caused when when upnp_forward_chain name is set to the same name as upnp_nat_chain in miniupnpd.conf

```
# chain names for netfilter (not used for pf or ipf).
# default is MINIUPNPD for both
upnp_forward_chain=MINIUPNPD
upnp_nat_chain=MINIUPNPD
```
^^^ bad config

if those config options are commented out or have differing values then there is no error

**Comment by miniupnp** [comment]
The error comes after this call : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter_nft/nftnlrdr.c#L129
```
	/* 'ip' family */
	result = chain_op(NFT_MSG_DELCHAIN, NFPROTO_IPV4, nft_table,
					  nft_prerouting_chain, NAT_CHAIN_TYPE, NF_INET_PRE_ROUTING, NF_IP_PRI_NAT_DST);
```
`nft_prerouting_chain` is empty

**Comment by miniupnp** [comment]
but it should not be empty if you set `upnp_nat_chain` in the .conf file

**Comment by miniupnp** [comment]
hum I was wrong it is
```
		result = chain_op(NFT_MSG_DELCHAIN, NFPROTO_IPV4, nft_table,
			  nft_postrouting_chain, NAT_CHAIN_TYPE, NF_INET_POST_ROUTING, NF_IP_PRI_NAT_SRC);
```
that fails. you should set ` upnp_nat_postrouting_chain` in the configuration file.

**Comment by JAMESMTL** [comment]
miniupnpd 2.2.0-RC1 master-c9f6ddd Sep 28 2020
using netfilter(nftables) backend

fyi : netfilter_nft/nftnlrdr.c:165:80: error: expected ‘;’ before ‘return’

```
# chain names for netfilter (not used for pf or ipf).
# default is MINIUPNPD for both
#upnp_forward_chain=MINIUPNPD
#upnp_nat_chain=MINIUPNPD
#upnp_nat_postrouting_chain=MINIUPNPD-POSTROUTING

./apps/upnpc/upnpc-shared -a 192.168.2.50 8096 8096 tcp 300
./apps/upnpc/upnpc-shared -d 8096 tcp

table inet miniupnpd {
        chain forward {
                type filter hook forward priority -25; policy accept;
        }
}
table ip miniupnpd {
        chain prerouting {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain postrouting {
                type nat hook postrouting priority srcnat; policy accept;
        }
}
table ip6 miniupnpd {
        chain prerouting {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain postrouting {
                type nat hook postrouting priority srcnat; policy accept;
        }
}
```

all good

```
# chain names for netfilter (not used for pf or ipf).
# default is MINIUPNPD for both
upnp_forward_chain=MINIUPNPD
upnp_nat_chain=MINIUPNPD
upnp_nat_postrouting_chain=MINIUPNPD-POSTROUTING

./apps/upnpc/upnpc-shared -a 192.168.2.50 8096 8096 tcp 300
./apps/upnpc/upnpc-shared -d 8096 tcp

table inet miniupnpd {
        chain MINIUPNPD {
                type filter hook forward priority -25; policy accept;
                iif "ppp0" th dport 8096 @nh,128,32 3232236082 @nh,72,8 6 accept
        }
}
table ip miniupnpd {
        chain MINIUPNPD {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain MINIUPNPD-POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
        }
}
table ip6 miniupnpd {
        chain MINIUPNPD {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain MINIUPNPD-POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
        }
}

Mon Sep 28 2020 13:45:59 EDTCENTURIONminiupnpd[19218]chain_op(5, 10, miniupnpd, , nat, 0, -100) send_batch failed -4
Mon Sep 28 2020 13:45:59 EDTCENTURIONminiupnpd[19218]send_batch: mnl_cb_run returned -1
```

gives error

**Comment by miniupnp** [comment]
the build is fixed (61d4aecb6e8da41a3e918d854bf63462807c93d8)

**Comment by miniupnp** [comment]
`init_redirect()` https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter_nft/nftnlrdr.c#L71
creates the tables and chains. it seems to work well...

**Comment by miniupnp** [comment]
I think I understand the problem : 
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/netfilter_nft/nftnlrdr_misc.c#L549

so if
```
upnp_forward_chain=MINIUPNPD
upnp_nat_chain=MINIUPNPD
```
the code will fail to recognize the rule as the "filter" rule.

**Comment by miniupnp** [comment]
@JAMESMTL could you check if branch https://github.com/miniupnp/miniupnp/tree/issue-481 indeed fixes it ?

**Comment by JAMESMTL** [comment]
sorry to say the problem still persists 

miniupnpd 2.2.0-RC1 issue-481-a352272 Oct 20 2020
using netfilter(nftables) backend

```
2020-10-20T09:54:18.157151-04:00 CENTURION miniupnpd[16789]: send_batch: mnl_cb_run returned -1
2020-10-20T09:54:18.157301-04:00 CENTURION miniupnpd[16789]: chain_op(5, 2, miniupnpd, œdÝU, nat, 4, 100) send_batch failed -4
```

**Comment by miniupnp** [comment]
> sorry to say the problem still persists
> 
> miniupnpd 2.2.0-RC1 issue-481-a352272 Oct 20 2020

@JAMESMTL 
`a352272` is not good, it MUST be the latest `3a17dea0`

**Comment by JAMESMTL** [comment]
oops, sorry about that

miniupnpd 2.2.0-RC1 issue-481-3a17dea Oct 22 2020
using netfilter(nftables) backend

```
upnp_forward_chain=MINIUPNPD
upnp_nat_chain=MINIUPNPD
upnp_nat_postrouting_chain=MINIUPNPD-POSTROUTING
```

Good news. multiple tests of adding and removing rules succeeded without any issues.

Unfortunately there is still a related secondary issue that occurs intermittently. Terminating the miniupnpd service may fail to remove the table and chains created on startup. 

I can only recreate the failure when upnp_forward_chain = upnp_nat_chain 


```
2020-10-22T10:15:07.550087-04:00 CENTURION systemd[1]: Stopping UPnP Internet Gateway Device Daemon...
2020-10-22T10:15:07.576980-04:00 CENTURION miniupnpd[24285]: send_batch: mnl_cb_run returned -1
2020-10-22T10:15:07.577056-04:00 CENTURION miniupnpd[24285]: chain_op(5, 2, miniupnpd, , nat, 0, -100) send_batch failed -4

table ip miniupnpd {
        chain MINIUPNPD {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain MINIUPNPD-POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
        }
}
table ip6 miniupnpd {
        chain MINIUPNPD {
                type nat hook prerouting priority dstnat; policy accept;
        }

        chain MINIUPNPD-POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
        }
}
```
Not only is the shutdown error intermittent, it is not consistent
```
2020-10-22T09:55:55.539582-04:00 CENTURION systemd[1]: Stopping UPnP Internet Gateway Device Daemon...
2020-10-22T09:55:55.560996-04:00 CENTURION miniupnpd[23552]: send_batch: mnl_cb_run returned -1
2020-10-22T09:55:55.561078-04:00 CENTURION miniupnpd[23552]: chain_op(5, 1, miniupnpd, , filter, 2, -25) send_batch failed -4
2020-10-22T09:55:55.576968-04:00 CENTURION miniupnpd[23552]: send_batch: mnl_cb_run returned -1
2020-10-22T09:55:55.577069-04:00 CENTURION miniupnpd[23552]: chain_op(5, 2, miniupnpd, , nat, 0, -100) send_batch failed -4
```

**Comment by miniupnp** [comment]
`enum nf_tables_msg_types` of value 5 is  `NFT_MSG_DELCHAIN`.
* NFPROTO_INET = 1
* NFPROTO_IPV4 = 2
`name` is the empty string, it should be the chain name.
* NF_INET_PRE_ROUTING  = 0
* NF_INET_FORWARD = 2
* NF_INET_POST_ROUTING = 10

**Comment by miniupnp** [comment]
@JAMESMTL please check again with 68cc351

**Comment by JAMESMTL** [comment]
miniupnpd 2.2.0-RC1 issue-481-68cc351 Oct 22 2020
using netfilter(nftables) backend

looks good. I no longer see any issues at shutdown.
